<a href="https://colab.research.google.com/github/sepehr-z/Empirical_Macroeconomics/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals:

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
print("for thousend time, Hello World!")

for thousend time, Hello World!


In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Introduction to Tensor

### Creating tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX =torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,3],[4,5,6,3],[9,8,7,3]],
                       [[1,2,3,2],[4,5,6,2],[9,8,7,2]]])
TENSOR

tensor([[[1, 2, 3, 3],
         [4, 5, 6, 3],
         [9, 8, 7, 3]],

        [[1, 2, 3, 2],
         [4, 5, 6, 2],
         [9, 8, 7, 2]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 3, 4])

In [17]:
TENSOR[1][1][1]

tensor(5)

### Random Tensors

Why random tensors?



In [18]:
# Creat a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0252, 0.5993, 0.1308, 0.6551],
        [0.8228, 0.9556, 0.5850, 0.6251],
        [0.1721, 0.4530, 0.0234, 0.4618]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor1 = torch.rand(10,10,10)
random_tensor1

tensor([[[1.7252e-01, 1.8954e-01, 2.3129e-01, 9.3921e-01, 7.3230e-01,
          9.0626e-02, 5.1014e-01, 4.4928e-01, 1.3478e-01, 5.3348e-03],
         [1.3611e-01, 9.6558e-01, 7.6210e-01, 7.3785e-02, 2.4593e-01,
          8.8105e-01, 5.0573e-01, 5.4639e-01, 3.5514e-01, 2.2645e-01],
         [3.7281e-01, 5.1346e-02, 6.3238e-01, 8.2326e-01, 7.3037e-01,
          1.1072e-01, 4.1664e-01, 2.4300e-01, 8.6450e-01, 1.3804e-01],
         [4.5358e-01, 1.9773e-01, 4.7738e-01, 5.1807e-01, 8.4926e-01,
          2.1597e-01, 2.5722e-01, 5.3650e-02, 7.8112e-01, 6.7593e-01],
         [8.1753e-01, 9.1244e-01, 3.8707e-01, 6.2902e-01, 7.8751e-01,
          4.7541e-01, 7.0508e-02, 1.3046e-01, 1.4947e-01, 8.4311e-01],
         [3.6130e-02, 3.1544e-01, 5.1219e-01, 7.9802e-01, 9.2769e-01,
          6.5633e-01, 2.5966e-02, 8.5814e-01, 6.7990e-01, 2.7683e-01],
         [2.9260e-01, 3.5688e-01, 3.8790e-02, 6.7188e-02, 5.0209e-01,
          2.6536e-01, 3.6459e-01, 7.0023e-01, 1.1108e-01, 8.0422e-01],
         [3.7

In [21]:
random_tensor1.ndim

3

In [22]:
# creat a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [23]:
# Creat a tensor of all zeros
zeros= torch.zeros(size=(3,4))
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Creat a tensor of all ones
ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [35]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# Create a tensor like
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [45]:
# Float 32 tensor
float_32_tensor= torch.tensor([3.0,6.0,9.0], dtype= None, # tensor datatype e.g. float32 or 16 or64
                              device=None, #what device is your tensor on e.g cpu or cuba
                              requires_grad=False) #whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [46]:
float_32_tensor.dtype

torch.float32

In [47]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors
1. Tensors not right datatype - use tensor.dtype
2. for shape use tensor.shape
3. to get on a right device use tensor.device

### Manipulating Tensors (Tensor Operation)

Tensor operation includes:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [52]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [53]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [54]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [56]:
torch.add(tensor,10)

tensor([11, 12, 13])